### PR TITLE
Refactor Makefile installation logic

### PR DESCRIPTION
**Pull request by puntolino**
The branching logic was doing the opposite of what was needed:

If the system is BSD or Darwin the command used should be `install`, otherwise (linux) `ginstall` should be used.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me, except for lacking the latest develop merge (CORE-435).

**Comment by puntolino** [comment]
> Looks good to me, except for lacking the latest develop merge (CORE-435).

Updated

**Review by ghost — APPROVED** [review]

**Comment by puntolino** [comment]
@leviathanch @ip-plank-security @saschabacardit any feedback on this?

**Review by saschabacardit — APPROVED** [review]

**Comment by ghost** [comment]
I belatedly realize that this does not build on linux anymore. `ginstall` is for macOS, if you need the GNU version, which is simply called `install` on linux. There is of course a `install` on macOS as well, but not the GNU version. I stumbled over this in CORE-453 and will fix it there, simply using `install` regardless of OS.

**Comment by puntolino** [comment]
ok, if you point me to the branch when available i can test it on MacOS!

**Pull request merged**
